system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: blog_server
  dir: ""
db:
  - user: remote
    password: 5Bs7)qg}6Q
    host: 47.79.84.19
    port: 3306
    db: blog
    debug: false
    source: mysql
  - user: remote
    password: 5Bs7)qg}6Q
    host: 47.79.84.19
    port: 3307
    db: blog
    debug: false
    source: mysql
es:
  addr: 47.79.84.19:9200
  is_https:
  username: elastic
  password: 5Bs7)qg}6Q
river:
  enable: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
    - schema: blog
      tables:
        - article_models
  rule:
    - schema: blog
      table: article_models
      index: article_index
      type: _doc
      field:
        tag_list: tag_list,list
  bulk_size: 128
jwt:
  expire: 3
  secret: xxx
  issuer: naseem
redis:
  addr: 47.79.84.19:6379
  password: 5Bs7)qg}6Q
  db: 2
site:
  siteInfo:
    title: test1
    log: ""
    beian: ""
    mode: 1
  project:
    title: golang-blog
    icon: /xxx.png
    webPath: uploads/index.html
  seo:
    keywords: 关键词测试
    description: 介绍测试
  login:
    qqLogin: true
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
  about:
    siteDate: "1"
    qq: "635220481"
    wechat: N4seem
    gitee: ""
    bilibili: ""
    github: ""
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 635220481@qq.com
  authCode: hshujaxozcmzbbgi
  sendNickname: naseem
  ssl: true
  tls: false
qq:
  appID: "1231231"
  appKey: '*******'
  redirect: "123131"
qiniu:
  enable: true
  accessKey: a1HaquccaTMHU_5IjZWQFCkQSdCDGhzJSGghRI8Z
  secretKey: iQV2LLT7_73INLavNm4lqgwAIF3UDpYDgwO0BTNc
  bucket: naseemblog
  uri: http://sugcd359c.hn-bkt.clouddn.com
  region: z2
  prefix: blog
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: ""
  nickname: ""
  avatar: ""
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - gif
  uploadDir: images001
