system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: blog_server
  dir: ""
db:
  user: root
  password: "123456"
  host: localhost
  port: 3306
  db: blog
  debug: false
  source: mysql
db1:
  user: ""
  password: ""
  host: ""
  port: 0
  db: ""
  debug: false
  source: ""
jwt:
  expire: 3
  secret: xxx
  issuer: naseem
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 2
site:
  siteInfo:
    title: test1
    log: ""
    beian: ""
    mode: 3
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  login:
    qqLogin: false
    usernamePwdLogin: false
    emailLogin: false
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
  about:
    siteDate: "1"
    qq: "2"
    wechat: "3"
    gitee: "4"
    bilibili: ""
    github: ""
email:
  domain: ""
  port: 0
  sendEmail: ""
  authCode: ""
  sendNickname: ""
  ssl: false
  tls: false
qq:
  appID: "1231231"
  appKey: '*******'
  redirect: "123131"
qiniu:
  enable: false
  accessKey: ""
  secretKey: ""
  bucket: ""
  uri: ""
  region: ""
  prefix: ""
  size: 0
ai:
  enable: false
  secretKey: ""
  nickname: ""
  avatar: ""
