system:
  ip:  # 需要提供具体的 IP 地址，例如 "192.168.1.1"
  port: 8080
  env: dev
  gin_mode: debug
log:
  app: blog_server
  dir:
ai:
  enable: 
  secretKey: 
  nickname: 
  avatar: 
redis:
  addr: 127.0.0.1:6379
  password:
  db: 2
jwt:
  expire: 3
  secret: xxx
  issuer: naseem
db:
  user: root
  password: 123456
  host: localhost
  port: 3306
  db: blog
  debug: false
  source: mysql